/**
 * An in-memory `AlarmEngine` for tests and the night simulator.
 *
 * Hand-written rather than generated by a mocking library, so it stays readable and can carry the
 * behaviours that matter: re-scheduling a known id overwrites, and `listScheduled` returns ids only
 * — the same limitation the real bridge has, so tests cannot accidentally rely on knowing when the
 * OS thinks an alarm fires.
 *
 * **It proves the logic around the engine, never the engine.** Whether AlarmKit actually fires, and
 * whether launch-on-dismissal is quick enough to re-arm, is what build step 5's spike measures. A
 * fake that fires on demand would answer neither question.
 */
import {
  UnsupportedError,
  type AlarmEngine,
  type AuthorisationState,
  type LaunchPayload,
} from './types';

export interface FakeAlarmEngineOptions {
  authorisation?: AuthorisationState;
  /** Simulate a bridge that cannot enumerate alarms, to exercise the reconcile fallback. */
  supportsListing?: boolean;
  configured?: boolean;
}

export class FakeAlarmEngine implements AlarmEngine {
  private alarms = new Map<string, number>();
  private auth: AuthorisationState;
  private launchPayload: LaunchPayload | null = null;
  private readonly supportsListing: boolean;
  private readonly configured: boolean;

  /** Every call, in order — so a test can assert what the app asked the OS to do. */
  readonly calls: { method: string; id?: string; at?: number }[] = [];

  constructor(options: FakeAlarmEngineOptions = {}) {
    this.auth = options.authorisation ?? 'granted';
    this.supportsListing = options.supportsListing ?? true;
    this.configured = options.configured ?? true;
  }

  async configure(): Promise<boolean> {
    this.calls.push({ method: 'configure' });
    return this.configured;
  }

  async schedule(id: string, at: number): Promise<void> {
    this.calls.push({ method: 'schedule', id, at });
    this.alarms.set(id, at);
  }

  async cancel(id: string): Promise<void> {
    this.calls.push({ method: 'cancel', id });
    this.alarms.delete(id);
  }

  async listScheduled(): Promise<string[]> {
    this.calls.push({ method: 'listScheduled' });
    if (!this.supportsListing) throw new UnsupportedError('listScheduled');
    return [...this.alarms.keys()].sort();
  }

  async authorisation(): Promise<AuthorisationState> {
    return this.auth;
  }

  async requestAuthorisation(): Promise<AuthorisationState> {
    if (this.auth === 'notDetermined') this.auth = 'granted';
    return this.auth;
  }

  async consumeLaunchPayload(): Promise<LaunchPayload | null> {
    const payload = this.launchPayload;
    this.launchPayload = null;
    return payload;
  }

  /** Test helper: pretend the OS launched the app by dismissing `alarmId`. */
  simulateLaunchFromAlarm(alarmId: string, payload: string | null = null): void {
    this.launchPayload = { alarmId, payload };
  }

  /** Test helper: what the OS holds, with instants, without recording a call. */
  peek(): { id: string; at: number }[] {
    return [...this.alarms].map(([id, at]) => ({ id, at })).sort((a, b) => a.at - b.at);
  }
}
